# Dependencies
markdown:         kramdown

# Permalinks
permalink:        pretty

# Setup
title:            Nathan 
tagline:          'Engineering, Programming, Learning'
description:      "Hello! I'm Nathan Jaggers, an engineer curious about the world and driven to learn more about it."
url:              'https://nrjaggers.github.io'
baseurl:          /

author:
  name:           'Nathan Jaggers'
  url:            https://github.com/NRJaggers

paginate:         5

# Custom vars
# version:          2.1.0

github:
  repo:           https://github.com/NRJaggers/nrjaggers.github.io

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-gist

# Build settings
exclude:
  - How_to_use_Hyde.md
  - vendor